---
AWSTemplateFormatVersion: "2010-09-09"

#https://docs.aws.amazon.com/pt_br/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html
Description: >
  Template CF para construir a funçao Lambda
  responsável por fazer a mudança de estado das instâncias EC2 da POC

Parameters:
  FunctionName:
    Type: String

  Handler:
    Type: String

  MemorySize:
    Type: Number

  PackageType:
    Type: String

  Runtime:
    Type: String

  Timeout:
    Type: Number

  RoleDescription:
    Type: String

  RoleName:
    Type: String

  FunctionDesc:
    Type: String

  S3ObjectKey:
    Type: String

  NotificationServiceURL:
    Type: String

Resources:

  RoleExecutionFuncaoLambda:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      Description: !Ref RoleDescription
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /poc/lambda/
      Policies:
        - PolicyName: poc-lambda-allow-s3-access-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: !Sub
                          - "${S3BucketFuncaoLambda}/*"
                          - {S3BucketFuncaoLambda: !ImportValue S3BucketFuncaoLambda}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  NotificationFunctionLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !ImportValue S3BucketName
        S3Key: !ImportValue S3ObjectKey
      Runtime: !Ref Runtime
      FunctionName: !Ref FunctionName
      Handler: !Ref Handler
      MemorySize: !Ref MemorySize
      PackageType: !Ref PackageType
      Timeout: !Ref Timeout
      Description: !Ref FunctionDesc
      Role: !GetAtt RoleExecutionFuncaoLambda.Arn
      Environment:
        Variables:
          NOTIFICATION_SERVICE_URL: !Ref NotificationServiceURL

Outputs:
  NotificationFunctionLambda:
    Description: Exporta o valor da ARN para ser usada em outro template
    Value: !GetAtt NotificationFunctionLambda.Arn
    Export:
      Name: NotificationFunctionLambda
