---
AWSTemplateFormatVersion: "2010-09-09"

#https://docs.aws.amazon.com/pt_br/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html
Description: >
  Primeiro template CF
  para construir a infraestrutura do bucket S3 que hospedará a função Lambda

Parameters:

  S3BucketName:
    Type: String

  S3ObjectKey:
    Type: String

Resources:

  S3BucketFuncaoLambda:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      AccessControl: Private

Outputs:
  S3ObjectKey:
    Value: !Ref S3ObjectKey
    Export:
      Name: S3ObjectKey

  S3BucketName:
    Value: !Ref S3BucketName
    Export:
      Name: S3BucketName

  S3BucketFuncaoLambda:
    Description: ARN do bucket S3 utilizado para armazenar o source-code
    Value: !GetAtt S3BucketFuncaoLambda.Arn
    Export:
      Name: S3BucketFuncaoLambda
